<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20151212173315.1"><vh>@settings</vh>
<v t="leo.20151212173315.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="leo.20151212173315.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20160921213353.1"><vh>2016fall 簡報與網誌樣板系統</vh></v>
<v t="amd.20160106095324.1" a="E"><vh>@path ./../</vh>
<v t="leo.20151213173830.1"><vh>假如要在近端檢視, 使用下列按鈕</vh>
<v t="leo.20151213085727.1"><vh>@button pelican-blog</vh></v>
</v>
<v t="amd.20151215180106.1" a="E"><vh>設定與開發</vh>
<v t="amd.20151216151325.1" a="E"><vh>@clean index.html</vh>
<v t="amd.20161004083800.1" a="E"><vh>html</vh>
<v t="amd.20161004083800.2"><vh>head</vh></v>
<v t="amd.20161004083800.5" a="E"><vh>body</vh>
<v t="amd.20161004083800.7"><vh>slides div</vh></v>
<v t="amd.20161004095719.1" a="E"><vh>封面投影片</vh>
<v t="amd.20161004095719.2"><vh>網路線-1</vh>
<v t="leo.20170623004106.1"><vh>newHeadline</vh></v>
</v>
<v t="leo.20170623005150.1"><vh>網路線-2</vh>
<v t="leo.20170623005154.1"><vh>newHeadline</vh></v>
</v>
<v t="leo.20170623011730.2"><vh>網路線-3</vh>
<v t="leo.20170623011730.1"><vh>newHeadline</vh></v>
</v>
<v t="leo.20170623110900.1"><vh>Fossil</vh>
<v t="leo.20170623110907.1"><vh>newHeadline</vh></v>
</v>
<v t="leo.20170623110936.1"><vh>CMSIMPLY</vh>
<v t="leo.20170623110941.1"><vh>newHeadline</vh></v>
</v>
<v t="leo.20170623111355.1"><vh>在VirtualBox中安裝Ubuntu16.04</vh>
<v t="leo.20170623111400.1"><vh>newHeadline</vh></v>
</v>
<v t="leo.20170623111404.2"><vh>在Ubuntu16.04中安裝nginx及設定網路</vh>
<v t="leo.20170623111404.1"><vh>newHeadline</vh></v>
</v>
<v t="leo.20170623111804.1"><vh>在Ubuntu 16.04 環境下啟動 Stunnel 與 Fossil SCM</vh>
<v t="leo.20170623111810.1"><vh>newHeadline</vh></v>
</v>
<v t="leo.20170623112218.1"><vh>END</vh>
<v t="leo.20170623112223.1"><vh>newHeadline</vh></v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20151213230723.1"><vh>Pelican 設定</vh>
<v t="leo.20151213230957.1"><vh>文章 Date 設定</vh></v>
<v t="leo.20151213230729.1"><vh>使用 summary plugin</vh></v>
</v>
<v t="amd.20151215170117.1"><vh>以下 pelicanconf.py 為近端與遠端的共同設定</vh></v>
<v t="leo.20151212173725.1"><vh>@edit pelicanconf.py</vh></v>
<v t="amd.20151215170221.1"><vh>以下 local_publishconf.py 為近端所使用的設定</vh></v>
<v t="leo.20151213085752.1"><vh>@edit local_publishconf.py</vh></v>
</v>
</v>
<v t="amd.20151215170350.1"><vh>以下為 content 目錄中的 md 檔案</vh></v>
<v t="amd.20151216001126.1"><vh>md 檔案範例</vh></v>
<v t="amd.20151215170031.1" a="E"><vh>@path ./../content</vh>
<v t="amd.20160106093454.1" a="E"><vh>yen 所寫的網誌文章</vh>
<v t="amd.20160727114506.1" a="E"><vh>201609</vh>
<v t="leo.20161114144444.1"><vh>@edit 20170427-1.md</vh></v>
<v t="leo.20170427145110.1"><vh>@edit 20170427-2.md</vh></v>
<v t="leo.20170427190753.1"><vh>@edit 20171427-3.md</vh></v>
</v>
</v>
</v>
<v t="amd.20160106094754.1"><vh>@path ./../content/pages</vh>
<v t="amd.20160106094829.1"><vh>yen 所寫的 pages 文章</vh>
<v t="amd.20160106094844.1"><vh>@edit pages_1.md</vh></v>
</v>
</v>
<v t="amd.20161004202833.1"><vh>@edit ../README.md</vh></v>
<v t="yen.20161022111056.1"><vh>@button https server</vh></v>
<v t="leo.20161209142152.1"><vh>@button https server</vh></v>
<v t="leo.20161209142134.1"><vh>@button ipv6 https server</vh></v>
<v t="yen.20161022151749.1"><vh>產生 .key 與 .crt</vh></v>
<v t="yen.20161105200127.1"><vh>選課人員名單</vh>
<v t="yen.20161105200140.1"><vh>@edit a.txt</vh></v>
<v t="yen.20161105200241.1"><vh>@edit b.txt</vh></v>
</v>
<v t="yen.20161105200145.1"><vh>分組名單</vh>
<v t="yen.20161105200154.1"><vh>@edit agroup.txt</vh></v>
<v t="yen.20161105200234.1"><vh>@edit bgroup.txt</vh></v>
</v>
<v t="leo.20161118210944.2" a="E"><vh>Recovered Nodes</vh>
<v t="leo.20161118210944.3"><vh>Recovered node "head" from @clean index.html</vh>
<v t="leo.20161118210944.4"><vh>old:head</vh></v>
<v t="leo.20161118210944.5"><vh>new:head</vh></v>
</v>
<v t="leo.20161118210944.6"><vh>Recovered node "body" from @clean index.html</vh>
<v t="leo.20161118210944.7"><vh>old:body</vh></v>
<v t="leo.20161118210944.8"><vh>new:body</vh></v>
</v>
<v t="leo.20161118210944.9"><vh>Recovered node "reveal div" from @clean index.html</vh>
<v t="leo.20161118210944.10"><vh>old:reveal div</vh></v>
<v t="leo.20161118210944.11"><vh>new:reveal div</vh></v>
</v>
<v t="leo.20161118210944.12"><vh>Recovered node "slides div" from @clean index.html</vh>
<v t="leo.20161118210944.13"><vh>old:slides div</vh></v>
<v t="leo.20161118210944.14"><vh>new:slides div</vh></v>
</v>
<v t="leo.20161118210944.15"><vh>Recovered node "封面投影片" from @clean index.html</vh>
<v t="leo.20161118210944.16"><vh>old:封面投影片</vh></v>
<v t="leo.20161118210944.17"><vh>new:封面投影片</vh></v>
</v>
<v t="leo.20161118210944.18"><vh>Recovered node "封面投影片內容" from @clean index.html</vh>
<v t="leo.20161118210944.19"><vh>old:封面投影片內容</vh></v>
<v t="leo.20161118210944.20"><vh>new:封面投影片內容</vh></v>
</v>
<v t="leo.20161118210944.21"><vh>Recovered node "快捷鍵" from @clean index.html</vh>
<v t="leo.20161118210944.22"><vh>old:快捷鍵</vh></v>
<v t="leo.20161118210944.23"><vh>new:快捷鍵</vh></v>
</v>
<v t="leo.20161118210944.24"><vh>Recovered node "投影片快捷鍵" from @clean index.html</vh>
<v t="leo.20161118210944.25"><vh>old:投影片快捷鍵</vh></v>
<v t="leo.20161118210944.26"><vh>new:投影片快捷鍵</vh></v>
</v>
<v t="leo.20161118210944.27"><vh>Recovered node "三大主題教學" from @clean index.html</vh>
<v t="leo.20161118210944.28"><vh>old:三大主題教學</vh></v>
<v t="leo.20161118210944.29"><vh>new:三大主題教學</vh></v>
</v>
<v t="leo.20161118210944.30"><vh>Recovered node "主題教學" from @clean index.html</vh>
<v t="leo.20161118210944.31"><vh>old:主題教學</vh></v>
<v t="leo.20161118210944.32"><vh>new:主題教學</vh></v>
</v>
<v t="leo.20161118210944.33"><vh>Recovered node "計算機程式在教什麼?" from @clean index.html</vh>
<v t="leo.20161118210944.34"><vh>old:計算機程式在教什麼?</vh></v>
<v t="leo.20161118210944.35"><vh>new:計算機程式在教什麼?</vh></v>
</v>
<v t="leo.20161118210944.36"><vh>Recovered node "主題教學內容" from @clean index.html</vh>
<v t="leo.20161118210944.37"><vh>old:主題教學內容</vh></v>
<v t="leo.20161118210944.38"><vh>new:主題教學內容</vh></v>
</v>
<v t="leo.20161118210944.39"><vh>Recovered node "計算機程式在教什麼?" from @clean index.html</vh>
<v t="leo.20161118210944.40"><vh>old:計算機程式在教什麼?</vh></v>
<v t="leo.20161118210944.41"><vh>new:計算機程式在教什麼?</vh></v>
</v>
<v t="leo.20161118210944.42"><vh>Recovered node "相關課程" from @clean index.html</vh>
<v t="leo.20161118210944.43"><vh>old:相關課程</vh></v>
<v t="leo.20161118210944.44"><vh>new:相關課程</vh></v>
</v>
<v t="leo.20161118210944.45"><vh>Recovered node "計算機程式系列課程" from @clean index.html</vh>
<v t="leo.20161118210944.46"><vh>old:計算機程式系列課程</vh></v>
<v t="leo.20161118210944.47"><vh>new:計算機程式系列課程</vh></v>
</v>
<v t="leo.20161118210944.48"><vh>Recovered node "創造力" from @clean index.html</vh>
<v t="leo.20161118210944.49"><vh>old:創造力</vh></v>
<v t="leo.20161118210944.50"><vh>new:創造力</vh></v>
</v>
<v t="leo.20161118210944.51"><vh>Recovered node "何謂創造力?" from @clean index.html</vh>
<v t="leo.20161118210944.52"><vh>old:何謂創造力?</vh></v>
<v t="leo.20161118210944.53"><vh>new:何謂創造力?</vh></v>
</v>
<v t="leo.20161118210944.54"><vh>Recovered node "創造力" from @clean index.html</vh>
<v t="leo.20161118210944.55"><vh>old:創造力</vh></v>
<v t="leo.20161118210944.56"><vh>new:創造力</vh></v>
</v>
<v t="leo.20161118210944.57"><vh>Recovered node "何謂創造力?" from @clean index.html</vh>
<v t="leo.20161118210944.58"><vh>old:何謂創造力?</vh></v>
<v t="leo.20161118210944.59"><vh>new:何謂創造力?</vh></v>
</v>
<v t="leo.20161118210944.60"><vh>Recovered node "所謂自學" from @clean index.html</vh>
<v t="leo.20161118210944.61"><vh>old:所謂自學</vh></v>
<v t="leo.20161118210944.62"><vh>new:所謂自學</vh></v>
</v>
<v t="leo.20161118210944.63"><vh>Recovered node "自學的訓練" from @clean index.html</vh>
<v t="leo.20161118210944.64"><vh>old:自學的訓練</vh></v>
<v t="leo.20161118210944.65"><vh>new:自學的訓練</vh></v>
</v>
<v t="leo.20161118210944.66"><vh>Recovered node "執行力" from @clean index.html</vh>
<v t="leo.20161118210944.67"><vh>old:執行力</vh></v>
<v t="leo.20161118210944.68"><vh>new:執行力</vh></v>
</v>
<v t="leo.20161118210944.69"><vh>Recovered node "高效執行力" from @clean index.html</vh>
<v t="leo.20161118210944.70"><vh>old:高效執行力</vh></v>
<v t="leo.20161118210944.71"><vh>new:高效執行力</vh></v>
</v>
<v t="leo.20161118210944.72"><vh>Recovered node "CP 課程倉儲" from @clean index.html</vh>
<v t="leo.20161118210944.73"><vh>old:CP 課程倉儲</vh></v>
<v t="leo.20161118210944.74"><vh>new:CP 課程倉儲</vh></v>
</v>
<v t="leo.20161118210944.75"><vh>Recovered node "課程時段與規劃" from @clean index.html</vh>
<v t="leo.20161118210944.76"><vh>old:課程時段與規劃</vh></v>
<v t="leo.20161118210944.77"><vh>new:課程時段與規劃</vh></v>
</v>
<v t="leo.20161118210944.78"><vh>Recovered node "規劃、Wiki 與網誌" from @clean index.html</vh>
<v t="leo.20161118210944.79"><vh>old:規劃、Wiki 與網誌</vh></v>
<v t="leo.20161118210944.80"><vh>new:規劃、Wiki 與網誌</vh></v>
</v>
<v t="leo.20161118210944.81"><vh>Recovered node "下載 miniconda 可攜環境" from @clean index.html</vh>
<v t="leo.20161118210944.82"><vh>old:下載 miniconda 可攜環境</vh></v>
<v t="leo.20161118210944.83"><vh>new:下載 miniconda 可攜環境</vh></v>
</v>
<v t="leo.20161118210944.84"><vh>Recovered node "下載可攜程式環境" from @clean index.html</vh>
<v t="leo.20161118210944.85"><vh>old:下載可攜程式環境</vh></v>
<v t="leo.20161118210944.86"><vh>new:下載可攜程式環境</vh></v>
</v>
<v t="leo.20161118210944.87"><vh>Recovered node "學員自評項目" from @clean index.html</vh>
<v t="leo.20161118210944.88"><vh>old:學員自評項目</vh></v>
<v t="leo.20161118210944.89"><vh>new:學員自評項目</vh></v>
</v>
<v t="leo.20161118210944.90"><vh>Recovered node "下載可攜程式環境" from @clean index.html</vh>
<v t="leo.20161118210944.91"><vh>old:下載可攜程式環境</vh></v>
<v t="leo.20161118210944.92"><vh>new:下載可攜程式環境</vh></v>
</v>
<v t="leo.20161118210944.93"><vh>Recovered node "自學力訓練" from @clean index.html</vh>
<v t="leo.20161118210944.94"><vh>old:自學力訓練</vh></v>
<v t="leo.20161118210944.95"><vh>new:自學力訓練</vh></v>
</v>
<v t="leo.20161118210944.96"><vh>Recovered node "自學的材料" from @clean index.html</vh>
<v t="leo.20161118210944.97"><vh>old:自學的材料</vh></v>
<v t="leo.20161118210944.98"><vh>new:自學的材料</vh></v>
</v>
<v t="leo.20161118210944.99"><vh>Recovered node "自學 Python3" from @clean index.html</vh>
<v t="leo.20161118210944.100"><vh>old:自學 Python3</vh></v>
<v t="leo.20161118210944.101"><vh>new:自學 Python3</vh></v>
</v>
<v t="leo.20161118210944.102"><vh>Recovered node "Python 執行環境" from @clean index.html</vh>
<v t="leo.20161118210944.103"><vh>old:Python 執行環境</vh></v>
<v t="leo.20161118210944.104"><vh>new:Python 執行環境</vh></v>
</v>
<v t="leo.20161118210944.105"><vh>Recovered node "在哪裡執行?" from @clean index.html</vh>
<v t="leo.20161118210944.106"><vh>old:在哪裡執行?</vh></v>
<v t="leo.20161118210944.107"><vh>new:在哪裡執行?</vh></v>
</v>
<v t="leo.20161118210944.108"><vh>Recovered node "Python 解譯器" from @clean index.html</vh>
<v t="leo.20161118210944.109"><vh>old:Python 解譯器</vh></v>
<v t="leo.20161118210944.110"><vh>new:Python 解譯器</vh></v>
</v>
<v t="leo.20161118210944.111"><vh>Recovered node "Python 解譯器" from @clean index.html</vh>
<v t="leo.20161118210944.112"><vh>old:Python 解譯器</vh></v>
<v t="leo.20161118210944.113"><vh>new:Python 解譯器</vh></v>
</v>
<v t="leo.20161118210944.114"><vh>Recovered node "Python 版次" from @clean index.html</vh>
<v t="leo.20161118210944.115"><vh>old:Python 版次</vh></v>
<v t="leo.20161118210944.116"><vh>new:Python 版次</vh></v>
</v>
<v t="leo.20161118210944.117"><vh>Recovered node "Python 2 或 3?" from @clean index.html</vh>
<v t="leo.20161118210944.118"><vh>old:Python 2 或 3?</vh></v>
<v t="leo.20161118210944.119"><vh>new:Python 2 或 3?</vh></v>
</v>
<v t="leo.20161118210944.120"><vh>Recovered node "執行力訓練" from @clean index.html</vh>
<v t="leo.20161118210944.121"><vh>old:執行力訓練</vh></v>
<v t="leo.20161118210944.122"><vh>new:執行力訓練</vh></v>
</v>
<v t="leo.20161118210944.123"><vh>Recovered node "程式練習主題" from @clean index.html</vh>
<v t="leo.20161118210944.124"><vh>old:程式練習主題</vh></v>
<v t="leo.20161118210944.125"><vh>new:程式練習主題</vh></v>
</v>
<v t="leo.20161118210944.126"><vh>Recovered node "程式專題" from @clean index.html</vh>
<v t="leo.20161118210944.127"><vh>old:程式專題</vh></v>
<v t="leo.20161118210944.128"><vh>new:程式專題</vh></v>
</v>
<v t="leo.20161118210944.129"><vh>Recovered node "如何進行上課分組與排座位" from @clean index.html</vh>
<v t="leo.20161118210944.130"><vh>old:如何進行上課分組與排座位</vh></v>
<v t="leo.20161118210944.131"><vh>new:如何進行上課分組與排座位</vh></v>
</v>
<v t="leo.20161118210944.132"><vh>Recovered node "課程分組排座位" from @clean index.html</vh>
<v t="leo.20161118210944.133"><vh>old:課程分組排座位</vh></v>
<v t="leo.20161118210944.134"><vh>new:課程分組排座位</vh></v>
</v>
<v t="leo.20161118210944.135"><vh>Recovered node "如何寫一個猜數字遊戲?" from @clean index.html</vh>
<v t="leo.20161118210944.136"><vh>old:如何寫一個猜數字遊戲?</vh></v>
<v t="leo.20161118210944.137"><vh>new:如何寫一個猜數字遊戲?</vh></v>
</v>
<v t="leo.20161118210944.138"><vh>Recovered node "猜數字遊戲" from @clean index.html</vh>
<v t="leo.20161118210944.139"><vh>old:猜數字遊戲</vh></v>
<v t="leo.20161118210944.140"><vh>new:猜數字遊戲</vh></v>
</v>
<v t="leo.20161118210944.141"><vh>Recovered node "如何繪製 2D 靜態圖?" from @clean index.html</vh>
<v t="leo.20161118210944.142"><vh>old:如何繪製 2D 靜態圖?</vh></v>
<v t="leo.20161118210944.143"><vh>new:如何繪製 2D 靜態圖?</vh></v>
</v>
<v t="leo.20161118210944.144"><vh>Recovered node "2D 繪圖" from @clean index.html</vh>
<v t="leo.20161118210944.145"><vh>old:2D 繪圖</vh></v>
<v t="leo.20161118210944.146"><vh>new:2D 繪圖</vh></v>
</v>
<v t="leo.20161118210944.147"><vh>Recovered node "如何製作一個簡單的網際遊戲?" from @clean index.html</vh>
<v t="leo.20161118210944.148"><vh>old:如何製作一個簡單的網際遊戲?</vh></v>
<v t="leo.20161118210944.149"><vh>new:如何製作一個簡單的網際遊戲?</vh></v>
</v>
<v t="leo.20161118210944.150"><vh>Recovered node "網際遊戲" from @clean index.html</vh>
<v t="leo.20161118210944.151"><vh>old:網際遊戲</vh></v>
<v t="leo.20161118210944.152"><vh>new:網際遊戲</vh></v>
</v>
<v t="leo.20161118210944.153"><vh>Recovered node "協同力訓練" from @clean index.html</vh>
<v t="leo.20161118210944.154"><vh>old:協同力訓練</vh></v>
<v t="leo.20161118210944.155"><vh>new:協同力訓練</vh></v>
</v>
<v t="leo.20161118210944.156"><vh>Recovered node "Github 帳號" from @clean index.html</vh>
<v t="leo.20161118210944.157"><vh>old:Github 帳號</vh></v>
<v t="leo.20161118210944.158"><vh>new:Github 帳號</vh></v>
</v>
<v t="leo.20161118210944.159"><vh>Recovered node "Github 倉儲網頁" from @clean index.html</vh>
<v t="leo.20161118210944.160"><vh>old:Github 倉儲網頁</vh></v>
<v t="leo.20161118210944.161"><vh>new:Github 倉儲網頁</vh></v>
</v>
<v t="leo.20161118210944.162"><vh>Recovered node "倉儲子模組串連" from @clean index.html</vh>
<v t="leo.20161118210944.163"><vh>old:倉儲子模組串連</vh></v>
<v t="leo.20161118210944.164"><vh>new:倉儲子模組串連</vh></v>
</v>
<v t="leo.20161118210944.165"><vh>Recovered node "學員作業網頁定版" from @clean index.html</vh>
<v t="leo.20161118210944.166"><vh>old:學員作業網頁定版</vh></v>
<v t="leo.20161118210944.167"><vh>new:學員作業網頁定版</vh></v>
</v>
<v t="leo.20161118210944.168"><vh>Recovered node "倉儲版本拉回請求" from @clean index.html</vh>
<v t="leo.20161118210944.169"><vh>old:倉儲版本拉回請求</vh></v>
<v t="leo.20161118210944.170"><vh>new:倉儲版本拉回請求</vh></v>
</v>
<v t="leo.20161118210944.171"><vh>Recovered node "Github 倉儲拉回請求" from @clean index.html</vh>
<v t="leo.20161118210944.172"><vh>old:Github 倉儲拉回請求</vh></v>
<v t="leo.20161118210944.173"><vh>new:Github 倉儲拉回請求</vh></v>
</v>
<v t="leo.20161118210944.174"><vh>Recovered node "開始學 Python" from @clean index.html</vh>
<v t="leo.20161118210944.175"><vh>old:開始學 Python</vh></v>
<v t="leo.20161118210944.176"><vh>new:開始學 Python</vh></v>
</v>
<v t="leo.20161118210944.177"><vh>Recovered node "Python 基本語法" from @clean index.html</vh>
<v t="leo.20161118210944.178"><vh>old:Python 基本語法</vh></v>
<v t="leo.20161118210944.179"><vh>new:Python 基本語法</vh></v>
</v>
<v t="leo.20161118210944.180"><vh>Recovered node "Python3 語法" from @clean index.html</vh>
<v t="leo.20161118210944.181"><vh>old:Python3 語法</vh></v>
<v t="leo.20161118210944.182"><vh>new:Python3 語法</vh></v>
</v>
<v t="leo.20161118210944.183"><vh>Recovered node "Python 迴圈" from @clean index.html</vh>
<v t="leo.20161118210944.184"><vh>old:Python 迴圈</vh></v>
<v t="leo.20161118210944.185"><vh>new:Python 迴圈</vh></v>
</v>
<v t="leo.20161118210944.186"><vh>Recovered node "for 迴圈用法" from @clean index.html</vh>
<v t="leo.20161118210944.187"><vh>old:for 迴圈用法</vh></v>
<v t="leo.20161118210944.188"><vh>new:for 迴圈用法</vh></v>
</v>
<v t="leo.20161118210944.189"><vh>Recovered node "Python 函式" from @clean index.html</vh>
<v t="leo.20161118210944.190"><vh>old:Python 函式</vh></v>
<v t="leo.20161118210944.191"><vh>new:Python 函式</vh></v>
</v>
<v t="leo.20161118210944.192"><vh>Recovered node "函式用法" from @clean index.html</vh>
<v t="leo.20161118210944.193"><vh>old:函式用法</vh></v>
<v t="leo.20161118210944.194"><vh>new:函式用法</vh></v>
</v>
<v t="leo.20161118210944.195"><vh>Recovered node "Python 數列" from @clean index.html</vh>
<v t="leo.20161118210944.196"><vh>old:Python 數列</vh></v>
<v t="leo.20161118210944.197"><vh>new:Python 數列</vh></v>
</v>
<v t="leo.20161118210944.198"><vh>Recovered node "數列用法" from @clean index.html</vh>
<v t="leo.20161118210944.199"><vh>old:數列用法</vh></v>
<v t="leo.20161118210944.200"><vh>new:數列用法</vh></v>
</v>
<v t="leo.20161118210944.201"><vh>Recovered node "分組程式" from @clean index.html</vh>
<v t="leo.20161118210944.202"><vh>old:分組程式</vh></v>
<v t="leo.20161118210944.203"><vh>new:分組程式</vh></v>
</v>
<v t="leo.20161118210944.204"><vh>Recovered node "分組程式內容" from @clean index.html</vh>
<v t="leo.20161118210944.205"><vh>old:分組程式內容</vh></v>
<v t="leo.20161118210944.206"><vh>new:分組程式內容</vh></v>
</v>
<v t="leo.20161118210944.207"><vh>Recovered node "猜數字遊戲" from @clean index.html</vh>
<v t="leo.20161118210944.208"><vh>old:猜數字遊戲</vh></v>
<v t="leo.20161118210944.209"><vh>new:猜數字遊戲</vh></v>
</v>
<v t="leo.20161118210944.210"><vh>Recovered node "遊戲邏輯" from @clean index.html</vh>
<v t="leo.20161118210944.211"><vh>old:遊戲邏輯</vh></v>
<v t="leo.20161118210944.212"><vh>new:遊戲邏輯</vh></v>
</v>
<v t="leo.20161118210944.213"><vh>Recovered node "2 D 繪圖" from @clean index.html</vh>
<v t="leo.20161118210944.214"><vh>old:2 D 繪圖</vh></v>
<v t="leo.20161118210944.215"><vh>new:2 D 繪圖</vh></v>
</v>
<v t="leo.20161118210944.216"><vh>Recovered node "Python 網際繪圖" from @clean index.html</vh>
<v t="leo.20161118210944.217"><vh>old:Python 網際繪圖</vh></v>
<v t="leo.20161118210944.218"><vh>new:Python 網際繪圖</vh></v>
</v>
<v t="leo.20161118210944.219"><vh>Recovered node "2 D 動畫" from @clean index.html</vh>
<v t="leo.20161118210944.220"><vh>old:2 D 動畫</vh></v>
<v t="leo.20161118210944.221"><vh>new:2 D 動畫</vh></v>
</v>
<v t="leo.20161118210944.222"><vh>Recovered node "網際動畫範例" from @clean index.html</vh>
<v t="leo.20161118210944.223"><vh>old:網際動畫範例</vh></v>
<v t="leo.20161118210944.224"><vh>new:網際動畫範例</vh></v>
</v>
<v t="leo.20161118210944.225"><vh>Recovered node "各式內容引用範例" from @clean index.html</vh>
<v t="leo.20161118210944.226"><vh>old:各式內容引用範例</vh></v>
<v t="leo.20161118210944.227"><vh>new:各式內容引用範例</vh></v>
</v>
<v t="leo.20161118210944.228"><vh>Recovered node "導入數學符號與方程式" from @clean index.html</vh>
<v t="leo.20161118210944.229"><vh>old:導入數學符號與方程式</vh></v>
<v t="leo.20161118210944.230"><vh>new:導入數學符號與方程式</vh></v>
</v>
<v t="leo.20161118210944.231"><vh>Recovered node "LaTeX 格式方程式" from @clean index.html</vh>
<v t="leo.20161118210944.232"><vh>old:LaTeX 格式方程式</vh></v>
<v t="leo.20161118210944.233"><vh>new:LaTeX 格式方程式</vh></v>
</v>
<v t="leo.20161118210944.234"><vh>Recovered node "導入縮排程式碼" from @clean index.html</vh>
<v t="leo.20161118210944.235"><vh>old:導入縮排程式碼</vh></v>
<v t="leo.20161118210944.236"><vh>new:導入縮排程式碼</vh></v>
</v>
<v t="leo.20161118210944.237"><vh>Recovered node "引用程式碼" from @clean index.html</vh>
<v t="leo.20161118210944.238"><vh>old:引用程式碼</vh></v>
<v t="leo.20161118210944.239"><vh>new:引用程式碼</vh></v>
</v>
<v t="leo.20161118210944.240" a="E"><vh>Recovered node "導入影片" from @clean index.html</vh>
<v t="leo.20161118210944.241"><vh>old:導入影片</vh></v>
<v t="leo.20161118210944.242"><vh>new:導入影片</vh></v>
</v>
<v t="leo.20161118210944.243" a="E"><vh>Recovered node "iframe 導入影片" from @clean index.html</vh>
<v t="leo.20161118210944.244"><vh>old:iframe 導入影片</vh></v>
<v t="leo.20161118210944.245"><vh>new:iframe 導入影片</vh></v>
</v>
</v>
<v t="leo.20161223145325.2"><vh>Recovered Nodes</vh>
<v t="leo.20161223145325.3"><vh>Recovered node "head" from @clean index.html</vh>
<v t="leo.20161223145325.4"><vh>old:head</vh></v>
<v t="leo.20161223145325.5"><vh>new:head</vh></v>
</v>
<v t="leo.20161223145325.6"><vh>Recovered node "封面投影片內容" from @clean index.html</vh>
<v t="leo.20161223145325.7"><vh>old:封面投影片內容</vh></v>
<v t="leo.20161223145325.8"><vh>new:封面投影片內容</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20151215170031.1"></t>
<t tx="amd.20151215170117.1"></t>
<t tx="amd.20151215170221.1"></t>
<t tx="amd.20151215170350.1"></t>
<t tx="amd.20151215180106.1"></t>
<t tx="amd.20151216001126.1">@language md
Title: 文章標題 (請注意各文章的標題不可相同, 比較保險的作法是冠上四個學號尾碼)
Date: 2016-09-2 12:00
Category: 類別
Tags: 標籤
Author: yen

這裡放入文章摘要

&lt;!-- PELICAN_END_SUMMARY --&gt;

這裡為文章主要內容

程式碼

&lt;pre class="brush: python;"&gt;
print("hello")
&lt;/pre&gt;</t>
<t tx="amd.20151216151325.1">@language xml
@tabwidth -4
@others
</t>
<t tx="amd.20160106093454.1"></t>
<t tx="amd.20160106094754.1"></t>
<t tx="amd.20160106094829.1"></t>
<t tx="amd.20160106095324.1"></t>
<t tx="amd.20160727114506.1"></t>
<t tx="amd.20160921213353.1"></t>
<t tx="amd.20161004083800.1">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;
</t>
<t tx="amd.20161004083800.2">
	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;40523123網際內容管理&lt;/title&gt;

		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
		&lt;meta name="author" content="Hakim El Hattab"&gt;

		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;
</t>
<t tx="amd.20161004083800.5">
@others

			&lt;/div&gt;

		&lt;/div&gt;

		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;

		&lt;script&gt;

			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	&lt;/body&gt;
</t>
<t tx="amd.20161004083800.7">
		&lt;div class="reveal"&gt;
@others

                              &lt;/section&gt;
</t>
<t tx="amd.20161004095719.1">                   
&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;40523123郝冠儒&lt;/h1&gt;
					&lt;h3&gt;網際內容管理簡報&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Writer&lt;/a&gt; / &lt;a href="https://github.com/s40523123"&gt;@40523123&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;網誌內容連結&lt;/a&gt;
				&lt;/section&gt;
</t>
<t tx="amd.20161004095719.2">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						

</t>
<t tx="leo.20151212173315.1"></t>
<t tx="leo.20151212173315.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="leo.20151212173315.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="leo.20151213085727.1">@language python
import os
#os.system("pelican content -o output -s local_publishconf.py -t theme/pelican-bootstrap3")
os.system("pelican content -o blog -s local_publishconf.py")
g.es("admin pelican 近端執行完畢")


</t>
<t tx="leo.20151213173830.1"></t>
<t tx="leo.20151213230723.1"></t>
<t tx="leo.20151213230729.1">利用

&lt;!-- PELICAN_END_SUMMARY --&gt;

來界定 Summary 摘要內容

前提, 必須設定 

PLUGIN_PATHS = ['plugin']

與

PLUGINS = ['liquid_tags.notebook', 'summary']

並且從 https://github.com/getpelican/pelican-plugins

取得 summary plugin</t>
<t tx="leo.20151213230957.1"># 設定網誌以 md 檔案建立的 file system date 為準, 無需自行設定

DEFAULT_DATE = 'fs'</t>
<t tx="leo.20161118210944.10">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20161118210944.100"># 自學 Python3

[Python3 程式範例](https://github.com/mdecourse/2016fallcp/blob/master/python3program.py)
### 在哪裡執行?
### 如何執行?
### 如何寫心得?
### 如何錄製操作過程?
</t>
<t tx="leo.20161118210944.101"></t>
<t tx="leo.20161118210944.102">(uncached) yen.20161011122957.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.103">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.104">@others
</t>
<t tx="leo.20161118210944.105">(uncached) yen.20161011122957.2
Diff...
+ # 在哪裡執行?
+ 
+ ### 單機操作系統中 (近端)
+ ### 單機連結到遠端主機中 (遠端)
+ ### 瀏覽器中 (網際端)
</t>
<t tx="leo.20161118210944.106"># 在哪裡執行?

### 單機操作系統中 (近端)
### 單機連結到遠端主機中 (遠端)
### 瀏覽器中 (網際端)
</t>
<t tx="leo.20161118210944.107"></t>
<t tx="leo.20161118210944.108">(uncached) yen.20161011123951.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.109">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.11">	&lt;body&gt;
@others
                              
				&lt;!-- Example of nested vertical slides --&gt;
</t>
<t tx="leo.20161118210944.110">@others
</t>
<t tx="leo.20161118210944.111">(uncached) yen.20161011123951.2
Diff...
+ # Python 解譯器
+ 
+ CPython: https://www.python.org/
+ 
+ (Anaconda: https://www.continuum.io/downloads)
+     
+ IronPython (.NET): http://ironpython.net/
+ 
+ Jython (Java): http://www.jython.org/
+ 
+ Pypy (Python): http://pypy.org/
+ 
+ Brython (Javascript): https://www.brython.info/
</t>
<t tx="leo.20161118210944.112"># Python 解譯器

CPython: https://www.python.org/

(Anaconda: https://www.continuum.io/downloads)
    
IronPython (.NET): http://ironpython.net/

Jython (Java): http://www.jython.org/

Pypy (Python): http://pypy.org/

Brython (Javascript): https://www.brython.info/
</t>
<t tx="leo.20161118210944.113"></t>
<t tx="leo.20161118210944.114">(uncached) yen.20161011124118.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.115">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.116">@others
</t>
<t tx="leo.20161118210944.117">(uncached) yen.20161011124118.2
Diff...
+ # Python 2 或 3?
+ 
+ ### 業界大部份仍以 2.7 版為主
+ 但是, 若沒有特別約束
+ ### 建議直接學習 Python3
</t>
<t tx="leo.20161118210944.118"># Python 2 或 3?

### 業界大部份仍以 2.7 版為主
但是, 若沒有特別約束
### 建議直接學習 Python3
</t>
<t tx="leo.20161118210944.119"></t>
<t tx="leo.20161118210944.12">(uncached) amd.20161004083800.7
Diff...
+ &lt;!-- Any section element inside of this container is displayed as a slide --&gt;
+ &lt;div class="slides"&gt;
+ @others
+ &lt;/div&gt;
  
- 		&lt;div class="reveal"&gt;
- @others
- &lt;p&gt;&lt;a href="https://vimeo.com/183954581"&gt;2016-09-23_fork_pull_requests&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
-                               &lt;/section&gt;
</t>
<t tx="leo.20161118210944.120">(uncached) yen.20161011125115.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161118210944.121">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161118210944.122">@others
</t>
<t tx="leo.20161118210944.123">(uncached) yen.20161016011920.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.124">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.125">@others
</t>
<t tx="leo.20161118210944.126">(uncached) yen.20161016011920.2
Diff...
+ # 計算機程式專題
+ 
+ * 如何進行上課分組與排座位?
+ * 如何寫一個猜數字遊戲?
+ * 如何繪製 2D 靜態圖?
+ * 如何製作一個簡單的網際遊戲?
</t>
<t tx="leo.20161118210944.127"># 計算機程式專題

* 如何進行上課分組與排座位?
* 如何寫一個猜數字遊戲?
* 如何繪製 2D 靜態圖?
* 如何製作一個簡單的網際遊戲?
</t>
<t tx="leo.20161118210944.128"></t>
<t tx="leo.20161118210944.129">(uncached) yen.20161011125115.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.13">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20161118210944.130">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.131">@others
</t>
<t tx="leo.20161118210944.132">(uncached) yen.20161011125115.3
Diff...
+ # 課程分組排座位
+ 
+ * 想像一下分組流程
+ * 請畫出流程圖
+ * 如何進行最好?
</t>
<t tx="leo.20161118210944.133"># 課程分組排座位

* 想像一下分組流程
* 請畫出流程圖
* 如何進行最好?
</t>
<t tx="leo.20161118210944.134"></t>
<t tx="leo.20161118210944.135">(uncached) yen.20161016012215.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.136">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.137">@others
</t>
<t tx="leo.20161118210944.138">(uncached) yen.20161016012215.2
Diff...
+ # 猜數字遊戲
+ 
+ * 單機執行還是瀏覽器執行?
+ * 請畫出流程圖
+ * 有沒有參考資料?
</t>
<t tx="leo.20161118210944.139"># 猜數字遊戲

* 單機執行還是瀏覽器執行?
* 請畫出流程圖
* 有沒有參考資料?
</t>
<t tx="leo.20161118210944.14">
		&lt;div class="reveal"&gt;
@others
&lt;p&gt;&lt;a href="https://vimeo.com/183954581"&gt;2016-09-23_fork_pull_requests&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
                              &lt;/section&gt;
</t>
<t tx="leo.20161118210944.140"></t>
<t tx="leo.20161118210944.141">(uncached) yen.20161016012253.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.142">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.143">@others
</t>
<t tx="leo.20161118210944.144">(uncached) yen.20161016012253.2
Diff...
+ # 2D 繪圖
+ 
+ * 單機執行還是瀏覽器執行?
+ * 請畫出流程圖
+ * 有沒有參考資料?
</t>
<t tx="leo.20161118210944.145"># 2D 繪圖

* 單機執行還是瀏覽器執行?
* 請畫出流程圖
* 有沒有參考資料?
</t>
<t tx="leo.20161118210944.146"></t>
<t tx="leo.20161118210944.147">(uncached) yen.20161016012402.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.148">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.149">@others
</t>
<t tx="leo.20161118210944.15">(uncached) amd.20161004095719.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
+ 
+ 						
- 			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
- @others
- 				&lt;section&gt;
- 					&lt;h2&gt;github_intro&lt;/h2&gt;
</t>
<t tx="leo.20161118210944.150">(uncached) yen.20161016012402.2
Diff...
+ # 網際遊戲
+ 
+ * 單機執行還是瀏覽器執行?
+ * 請畫出流程圖
+ * 有沒有參考資料?
</t>
<t tx="leo.20161118210944.151"># 網際遊戲

* 單機執行還是瀏覽器執行?
* 請畫出流程圖
* 有沒有參考資料?
</t>
<t tx="leo.20161118210944.152"></t>
<t tx="leo.20161118210944.153">(uncached) yen.20161011143808.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161118210944.154">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161118210944.155">@others
</t>
<t tx="leo.20161118210944.156">(uncached) yen.20161011143808.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.157">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.158">@others
</t>
<t tx="leo.20161118210944.159">(uncached) yen.20161011143808.3
Diff...
+ # Github 倉儲網頁
+ 
+ ####建立個人 Github 網頁 (帳號.github.io)
+ ####建立個人課程作業網頁 (納入投影片與網誌架構)
+ ####組長建立分組的評量網頁 (納入投影片與網誌架構)
</t>
<t tx="leo.20161118210944.16">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.160"># Github 倉儲網頁

####建立個人 Github 網頁 (帳號.github.io)
####建立個人課程作業網頁 (納入投影片與網誌架構)
####組長建立分組的評量網頁 (納入投影片與網誌架構)
</t>
<t tx="leo.20161118210944.161"></t>
<t tx="leo.20161118210944.162">(uncached) yen.20161011144113.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.163">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.164">@others
</t>
<t tx="leo.20161118210944.165">(uncached) yen.20161011144113.2
Diff...
+ # 學員作業網頁定版
+ 
+ ###個人作業網頁內容可以隨時改版
+ ###分組評量網頁必須在指定時間前定版
+ ###Github 倉儲 gh-pages分支與子模組應用
</t>
<t tx="leo.20161118210944.166"># 學員作業網頁定版

###個人作業網頁內容可以隨時改版
###分組評量網頁必須在指定時間前定版
###Github 倉儲 gh-pages分支與子模組應用
</t>
<t tx="leo.20161118210944.167"></t>
<t tx="leo.20161118210944.168">(uncached) yen.20161011144715.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.169">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.17">
			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
@others
				&lt;section&gt;
					&lt;h2&gt;github_intro&lt;/h2&gt;
</t>
<t tx="leo.20161118210944.170">@others
</t>
<t tx="leo.20161118210944.171">(uncached) yen.20161011144715.2
Diff...
+ # Github 倉儲拉回請求
+ 
+ ####分組倉儲 Collaborators 設定
+ ####分組倉儲版本 Pull Requests 練習
+ ####各組員實際操作影片錄製
+ ####操作影片加字幕以及影片檔相加
</t>
<t tx="leo.20161118210944.172"># Github 倉儲拉回請求

####分組倉儲 Collaborators 設定
####分組倉儲版本 Pull Requests 練習
####各組員實際操作影片錄製
####操作影片加字幕以及影片檔相加
</t>
<t tx="leo.20161118210944.173"></t>
<t tx="leo.20161118210944.174">(uncached) yen.20161011145156.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161118210944.175">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161118210944.176">@others
</t>
<t tx="leo.20161118210944.177">(uncached) yen.20161011145156.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.178">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.179">@others
</t>
<t tx="leo.20161118210944.18">(uncached) amd.20161004095719.2
Diff...
+ # 2016Fall 計算機程式課程
- 			&lt;div class="slides"&gt;
- 				&lt;section&gt;
- 					&lt;h1&gt;2016Fall CPA 計算機程式課程&lt;/h1&gt;
- 					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
- 					&lt;p&gt;
- 						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
- 					&lt;/p&gt;
-                     &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
- 				&lt;/section&gt;
  
+ ### 虎科大機械設計工程系
+ 
+ &lt;small&gt;
+ Created by [KMOLab](http://chiamingyen.github.io/kmolab/blog/)
+ &lt;/small&gt;
+ 
+ [blog](blog/index.html)
+ 
</t>
<t tx="leo.20161118210944.180">(uncached) yen.20161011145156.3
Diff...
+ # Python3 語法
+ 
+ ####print()
+ ####input()
+ ####變數名稱與關鍵字
</t>
<t tx="leo.20161118210944.181"># Python3 語法

####print()
####input()
####變數名稱與關鍵字
</t>
<t tx="leo.20161118210944.182"></t>
<t tx="leo.20161118210944.183">(uncached) yen.20161011145156.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.184">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.185">@others
</t>
<t tx="leo.20161118210944.186">(uncached) yen.20161011145156.5
Diff...
+ # for 迴圈用法
+ 
+ ###Python 程式縮排
+ ###for i in range(5)：
+ ###數列與 iterator
+ 
</t>
<t tx="leo.20161118210944.187"># for 迴圈用法

###Python 程式縮排
###for i in range(5)：
###數列與 iterator

</t>
<t tx="leo.20161118210944.188"></t>
<t tx="leo.20161118210944.189">(uncached) yen.20161011145156.6
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.19"># 2016Fall 計算機程式課程

### 虎科大機械設計工程系

&lt;small&gt;
Created by [KMOLab](http://chiamingyen.github.io/kmolab/blog/)
&lt;/small&gt;

[blog](blog/index.html)

</t>
<t tx="leo.20161118210944.190">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.191">@others
</t>
<t tx="leo.20161118210944.192">(uncached) yen.20161011145156.7
Diff...
+ # 函式用法
+ 
+ ####函式定義
+ ####函式呼叫與傳值
+ ####函式載入順序
</t>
<t tx="leo.20161118210944.193"># 函式用法

####函式定義
####函式呼叫與傳值
####函式載入順序
</t>
<t tx="leo.20161118210944.194"></t>
<t tx="leo.20161118210944.195">(uncached) yen.20161011145755.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.196">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.197">@others
</t>
<t tx="leo.20161118210944.198">(uncached) yen.20161011145755.2
Diff...
+ # 數列用法
+ 
+ ####數列與索引
+ ####數列與字串
+ ####數列排序
</t>
<t tx="leo.20161118210944.199"># 數列用法

####數列與索引
####數列與字串
####數列排序
</t>
<t tx="leo.20161118210944.2"></t>
<t tx="leo.20161118210944.20">			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;2016Fall CPA 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20161118210944.200"></t>
<t tx="leo.20161118210944.201">(uncached) yen.20161011145952.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.202">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.203">@others
</t>
<t tx="leo.20161118210944.204">(uncached) yen.20161011145952.2
Diff...
+ # 分組程式內容
+ 
+ ####讀取原始資料內容
+ ####設法分割資料, 納入數列
+ ####根據設計邏輯進行資料處理
</t>
<t tx="leo.20161118210944.205"># 分組程式內容

####讀取原始資料內容
####設法分割資料, 納入數列
####根據設計邏輯進行資料處理
</t>
<t tx="leo.20161118210944.206"></t>
<t tx="leo.20161118210944.207">(uncached) yen.20161011150316.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.208">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.209">@others
</t>
<t tx="leo.20161118210944.21">(uncached) yen.20161016023122.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.210">(uncached) yen.20161011150316.2
Diff...
+ # 遊戲邏輯
+ 
+ ####1-100 中隨機取一個數字作為答案
+ ####設法讓使用者猜這個數字 (接受輸入)
+ ####使用每猜一次都回答比答案大或小
+ ####能在一定次數中猜對者獲勝
+ ####在單機或網際執行程式?
</t>
<t tx="leo.20161118210944.211"># 遊戲邏輯

####1-100 中隨機取一個數字作為答案
####設法讓使用者猜這個數字 (接受輸入)
####使用每猜一次都回答比答案大或小
####能在一定次數中猜對者獲勝
####在單機或網際執行程式?
</t>
<t tx="leo.20161118210944.212"></t>
<t tx="leo.20161118210944.213">(uncached) yen.20161011150126.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.214">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.215">@others
</t>
<t tx="leo.20161118210944.216">(uncached) yen.20161011150126.2
Diff...
+ # Python 網際繪圖
+ 
+ ####Brython 簡介
+ ####Brython 執行設定
+ ####基本繪圖練習 (五芒星、正齒輪與各國國旗)
</t>
<t tx="leo.20161118210944.217"># Python 網際繪圖

####Brython 簡介
####Brython 執行設定
####基本繪圖練習 (五芒星、正齒輪與各國國旗)
</t>
<t tx="leo.20161118210944.218"></t>
<t tx="leo.20161118210944.219">(uncached) yen.20161011150901.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.22">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.220">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.221">@others
</t>
<t tx="leo.20161118210944.222">(uncached) yen.20161011150901.2
Diff...
+ # 網際動畫範例
+ 
+ ####機構模擬
+ ####猜顏色遊戲
+ ####網際對戰遊戲
</t>
<t tx="leo.20161118210944.223"># 網際動畫範例

####機構模擬
####猜顏色遊戲
####網際對戰遊戲
</t>
<t tx="leo.20161118210944.224"></t>
<t tx="leo.20161118210944.225">(uncached) yen.20161016012809.1
Diff...
+ &lt;section&gt;
  @others
- 				&lt;iframe src="https://player.vimeo.com/video/183954581" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ &lt;/section&gt;</t>
<t tx="leo.20161118210944.226">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161118210944.227">@others
				&lt;iframe src="https://player.vimeo.com/video/183954581" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161118210944.228">(uncached) yen.20161016012809.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ &lt;!-- 請注意, @others 不可以內縮 --&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.229">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20161118210944.23">@others
</t>
<t tx="leo.20161118210944.230">@others
</t>
<t tx="leo.20161118210944.231">(uncached) yen.20161016012809.3
Diff...
+ # 數學符號與方程式
+ 
+ Inline math equations go in like so: $\omega = d\phi / dt$. Display
+ math should get its own line and be put in in double-dollarsigns:
+ 
+ $$I = \int \rho R^{2} dV$$
</t>
<t tx="leo.20161118210944.232"># 數學符號與方程式

Inline math equations go in like so: $\omega = d\phi / dt$. Display
math should get its own line and be put in in double-dollarsigns:

$$I = \int \rho R^{2} dV$$
</t>
<t tx="leo.20161118210944.233"></t>
<t tx="leo.20161118210944.234">(uncached) yen.20161016012809.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ &lt;!-- 請注意, @others 不可以內縮 --&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.235">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20161118210944.236">@others
</t>
<t tx="leo.20161118210944.237">(uncached) yen.20161016012809.5
Diff...
+ ## 利用 Markdown 寫投影片
+ 以下利用 Markdown 格式展示 Python 程式碼:
+ ```
  @language python
+ # use threading and subprocess to threading the make process
+ import os
+ import subprocess
+ import threading
+ 
+ def domake():
+     
+     path = "../exposed/api/exposed"
+     ubuntu = "../Ubuntu"
+     
+     # create obj path
+     
+     if not os.path.exists(path+"/../obj"):
+         os.makedirs(path+"/../obj")
+     
+     subprocess.call(["make", "clean"], cwd=path)
+     subprocess.call("make", cwd=path)
+     subprocess.call(["cp", "{libslvs.so, _slvs.so, slvs.py}", ubuntu], cwd=path)
+     subprocess.call(["python3", "circle_ex.py"], cwd=path+"/"+ubuntu)
+     
+ make = threading.Thread(target=domake)
+ make.start()
+ ```
</t>
<t tx="leo.20161118210944.238">## 利用 Markdown 寫投影片
以下利用 Markdown 格式展示 Python 程式碼:
```
@language python
# use threading and subprocess to threading the make process
import os
import subprocess
import threading

def domake():
    
    path = "../exposed/api/exposed"
    ubuntu = "../Ubuntu"
    
    # create obj path
    
    if not os.path.exists(path+"/../obj"):
        os.makedirs(path+"/../obj")
    
    subprocess.call(["make", "clean"], cwd=path)
    subprocess.call("make", cwd=path)
    subprocess.call(["cp", "{libslvs.so, _slvs.so, slvs.py}", ubuntu], cwd=path)
    subprocess.call(["python3", "circle_ex.py"], cwd=path+"/"+ubuntu)
    
make = threading.Thread(target=domake)
make.start()
```
</t>
<t tx="leo.20161118210944.239">@language python
</t>
<t tx="leo.20161118210944.24">(uncached) yen.20161016023122.2
Diff...
+ # 投影片快捷鍵
+ 
+ * 利用箭頭上下前後換頁
+ * 按 f 鍵進入全螢幕模式 (full screen)
+ * 按 s 鍵可以顯示投影片筆記 (show)
+ * 按 o 鍵可以切換單張或全域檢視 (overview)
+ * 按 b 或 . 鍵可以切換螢幕黑屏 (black)
+ * 按 Esc 可以退出全螢幕或全域檢視 (Escape)
+ 
</t>
<t tx="leo.20161118210944.240">(uncached) yen.20161016012809.6
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
  
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
+ 
+ 
- 				
+ 						
? ++
-                                &lt;section&gt;
- 					&lt;h2&gt;fork_pull_requests&lt;/h2&gt;
</t>
<t tx="leo.20161118210944.241">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.242">@others

				&lt;/section&gt;
				
                               &lt;section&gt;
					&lt;h2&gt;fork_pull_requests&lt;/h2&gt;
</t>
<t tx="leo.20161118210944.243">(uncached) yen.20161016012809.7
Diff...
+ ## 使用 iframe 導入影片
+ 
+ ### 導入影片 template
+ 
</t>
<t tx="leo.20161118210944.244">## 使用 iframe 導入影片

### 導入影片 template

</t>
<t tx="leo.20161118210944.245"></t>
<t tx="leo.20161118210944.25"># 投影片快捷鍵

* 利用箭頭上下前後換頁
* 按 f 鍵進入全螢幕模式 (full screen)
* 按 s 鍵可以顯示投影片筆記 (show)
* 按 o 鍵可以切換單張或全域檢視 (overview)
* 按 b 或 . 鍵可以切換螢幕黑屏 (black)
* 按 Esc 可以退出全螢幕或全域檢視 (Escape)

</t>
<t tx="leo.20161118210944.26"></t>
<t tx="leo.20161118210944.27">(uncached) amd.20161004104820.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;
</t>
<t tx="leo.20161118210944.28">&lt;section&gt;
@others
&lt;/section&gt;
</t>
<t tx="leo.20161118210944.29">@others
</t>
<t tx="leo.20161118210944.3">(uncached) amd.20161004083800.2
Diff...
+ &lt;head&gt;
+     &lt;meta charset="utf-8"&gt;
+ &lt;title&gt;    
+ 40523123 郝冠儒的計算機課程
+ &lt;/title&gt;
+     &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
+     &lt;meta name="author" content="Hakim El Hattab"&gt;
+     
+     &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
+     &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
+     
+     &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
+     
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
+     
+     &lt;!-- Theme used for syntax highlighting of code --&gt;
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
  
- 	&lt;head&gt;
- 		&lt;meta charset="utf-8"&gt;
+     &lt;!-- Printing and PDF exports --&gt;
+     &lt;script&gt;
+         var link = document.createElement( 'link' );
+         link.rel = 'stylesheet';
+         link.type = 'text/css';
+         link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
+         document.getElementsByTagName( 'head' )[0].appendChild( link );
+     &lt;/script&gt;
  
- 		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;
+     &lt;!--[if lt IE 9]&gt;
+     &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
+     &lt;![endif]--&gt;
+ &lt;/head&gt;
  
- 		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
- 		&lt;meta name="author" content="Hakim El Hattab"&gt;
- 
- 		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
- 		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
- 
- 		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
- 
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
- 
- 		&lt;!-- Theme used for syntax highlighting of code --&gt;
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
- 
- 		&lt;!-- Printing and PDF exports --&gt;
- 		&lt;script&gt;
- 			var link = document.createElement( 'link' );
- 			link.rel = 'stylesheet';
- 			link.type = 'text/css';
- 			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
- 			document.getElementsByTagName( 'head' )[0].appendChild( link );
- 		&lt;/script&gt;
- 
- 		&lt;!--[if lt IE 9]&gt;
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
- 		&lt;![endif]--&gt;
- 	&lt;/head&gt;
</t>
<t tx="leo.20161118210944.30">(uncached) amd.20161004104641.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.31">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.32">@others
</t>
<t tx="leo.20161118210944.33">(uncached) amd.20161004104641.2
Diff...
+ # 計算機程式在教什麼?
+ 
+ ## 創造力
+ ## 表達力
+ 以及
+ ## 協同力
+ 
</t>
<t tx="leo.20161118210944.34"># 計算機程式在教什麼?

## 創造力
## 表達力
以及
## 協同力

</t>
<t tx="leo.20161118210944.35"></t>
<t tx="leo.20161118210944.36">(uncached) yen.20161011155543.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.37">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.38">@others
</t>
<t tx="leo.20161118210944.39">(uncached) yen.20161011155543.2
Diff...
+ # 計算機程式在教什麼?
+ 
+ ## &lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;&lt;small&gt;=自學力+程式力+想像力&lt;/small&gt;
+ ## &lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;&lt;small&gt;=口語+文字+2D+3D+理論+實體&lt;/small&gt;
+ &lt;span style="color:#00FF80"&gt;以及&lt;/span&gt;
+ ## &lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;&lt;small&gt;=電腦+網路+工具+專案&lt;/small&gt;
+ 
</t>
<t tx="leo.20161118210944.4">&lt;head&gt;
    &lt;meta charset="utf-8"&gt;
&lt;title&gt;    
2016 Fall 計算機程式課程
&lt;/title&gt;
    &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
    &lt;meta name="author" content="Hakim El Hattab"&gt;
    
    &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
    &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
    
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
    
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
    
    &lt;!-- Theme used for syntax highlighting of code --&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;

</t>
<t tx="leo.20161118210944.40"># 計算機程式在教什麼?

## &lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;&lt;small&gt;=自學力+程式力+想像力&lt;/small&gt;
## &lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;&lt;small&gt;=口語+文字+2D+3D+理論+實體&lt;/small&gt;
&lt;span style="color:#00FF80"&gt;以及&lt;/span&gt;
## &lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;&lt;small&gt;=電腦+網路+工具+專案&lt;/small&gt;

</t>
<t tx="leo.20161118210944.41"></t>
<t tx="leo.20161118210944.42">(uncached) yen.20161011115740.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.43">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.44">@others
</t>
<t tx="leo.20161118210944.45">(uncached) yen.20161011115740.2
Diff...
+ # 計算機程式系列課程
+ 
+ ## 網際內容管理
+ ## 電腦輔助設計實習
+ &lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
+ ## 協同產品設計實習
+ 也在研習&lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;、&lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;與&lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;
+ 
</t>
<t tx="leo.20161118210944.46"># 計算機程式系列課程

## 網際內容管理
## 電腦輔助設計實習
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 協同產品設計實習
也在研習&lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;、&lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;與&lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;

</t>
<t tx="leo.20161118210944.47"></t>
<t tx="leo.20161118210944.48">(uncached) amd.20161004105131.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.49">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.5">
	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;

		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
		&lt;meta name="author" content="Hakim El Hattab"&gt;

		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;
</t>
<t tx="leo.20161118210944.50">@others
</t>
<t tx="leo.20161118210944.51">(uncached) amd.20161004105131.2
Diff...
+ # 何謂創造力?
+ 
+ ## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;自學&lt;/span&gt;
+ ## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;可執行&lt;/span&gt;流程
+ &lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
+ ## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;想像力&lt;/span&gt;
+ 
</t>
<t tx="leo.20161118210944.52"># 何謂創造力?

## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;自學&lt;/span&gt;
## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;可執行&lt;/span&gt;流程
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;想像力&lt;/span&gt;

</t>
<t tx="leo.20161118210944.53"></t>
<t tx="leo.20161118210944.54">(uncached) yen.20161011114704.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.55">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.56">@others
</t>
<t tx="leo.20161118210944.57">(uncached) yen.20161011114704.2
Diff...
+ # 何謂創造力?
+ 
+ ## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;自學-&gt;&lt;span style="color:#FFFF00"&gt;不一定都要別人教&lt;/span&gt;
+ ## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;可執行流程-&gt;展現&lt;span style="color:#FFFF00"&gt;執行力&lt;/span&gt;
+ &lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
+ ## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;想像力-&gt;不受限, &lt;span style="color:#FFFF00"&gt;積極進行改造&lt;/span&gt;
+ 
</t>
<t tx="leo.20161118210944.58"># 何謂創造力?

## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;自學-&gt;&lt;span style="color:#FFFF00"&gt;不一定都要別人教&lt;/span&gt;
## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;可執行流程-&gt;展現&lt;span style="color:#FFFF00"&gt;執行力&lt;/span&gt;
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;想像力-&gt;不受限, &lt;span style="color:#FFFF00"&gt;積極進行改造&lt;/span&gt;

</t>
<t tx="leo.20161118210944.59"></t>
<t tx="leo.20161118210944.6">(uncached) amd.20161004083800.5
Diff...
+ &lt;body&gt;
+ @others
+ &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
+ &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
+ &lt;script&gt;
+         // More info https://github.com/hakimel/reveal.js#configuration
+         Reveal.initialize({
+             controls: true,
+             progress: true,
+             history: true,
+             center: true,
  
+             transition: 'slide', // none/fade/slide/convex/concave/zoom
- @others
- 				&lt;section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Vertical Slides&lt;/h2&gt;
- 						&lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
- 						&lt;p&gt;Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.&lt;/p&gt;
- 						&lt;br&gt;
- 						&lt;a href="#" class="navigate-down"&gt;
- 							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
- 						&lt;/a&gt;
- 					&lt;/section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Basement Level 1&lt;/h2&gt;
- 						&lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
- 					&lt;/section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
- 						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
- 						&lt;br&gt;
- 						&lt;a href="#/2"&gt;
- 							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
- 						&lt;/a&gt;
- 					&lt;/section&gt;
- 				&lt;/section&gt;
  
- 				&lt;section&gt;
- 					&lt;h2&gt;Slides&lt;/h2&gt;
- 					&lt;p&gt;
- 						Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Point of View&lt;/h2&gt;
- 					&lt;p&gt;
- 						Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
- 					&lt;/p&gt;
- 					&lt;p&gt;
- 						Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Touch Optimized&lt;/h2&gt;
- 					&lt;p&gt;
- 						Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section data-markdown&gt;
- 					&lt;script type="text/template"&gt;
- 						## Markdown support
- 
- 						Write content using inline or external Markdown.
- 						Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
- 
- 						```
- 						&lt;section data-markdown&gt;
- 						  ## Markdown support
- 
- 						  Write content using inline or external Markdown.
- 						  Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
- 						&lt;/section&gt;
- 						```
- 					&lt;/script&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;section id="fragments"&gt;
- 						&lt;h2&gt;Fragments&lt;/h2&gt;
- 						&lt;p&gt;Hit the next arrow...&lt;/p&gt;
- 						&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
- 						&lt;p&gt;&lt;span class="fragment"&gt;... a&lt;/span&gt; &lt;span class="fragment"&gt;fragmented&lt;/span&gt; &lt;span class="fragment"&gt;slide.&lt;/span&gt;&lt;/p&gt;
- 
- 						&lt;aside class="notes"&gt;
- 							This slide has fragments which are also stepped through in the notes window.
- 						&lt;/aside&gt;
- 					&lt;/section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Fragment Styles&lt;/h2&gt;
- 						&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
- 						&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
- 						&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
- 						&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
- 						&lt;p class="fragment fade-up"&gt;fade-up (also down, left and right!)&lt;/p&gt;
- 						&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
- 						&lt;p&gt;Highlight &lt;span class="fragment highlight-red"&gt;red&lt;/span&gt; &lt;span class="fragment highlight-blue"&gt;blue&lt;/span&gt; &lt;span class="fragment highlight-green"&gt;green&lt;/span&gt;&lt;/p&gt;
- 					&lt;/section&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section id="transitions"&gt;
- 					&lt;h2&gt;Transition Styles&lt;/h2&gt;
- 					&lt;p&gt;
- 						You can select from different transitions, like: &lt;br&gt;
- 						&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
- 						&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
- 						&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
- 						&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
- 						&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
- 						&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section id="themes"&gt;
- 					&lt;h2&gt;Themes&lt;/h2&gt;
- 					&lt;p&gt;
- 						reveal.js comes with a few themes built in: &lt;br&gt;
- 						&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; &lt;br&gt;
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;section data-background="#dddddd"&gt;
- 						&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
- 						&lt;p&gt;
- 							Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
- 						&lt;/p&gt;
- 						&lt;a href="#" class="navigate-down"&gt;
- 							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
- 						&lt;/a&gt;
- 					&lt;/section&gt;
- 					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
- 						&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
- 						&lt;pre&gt;&lt;code class="hljs"&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
- 					&lt;/section&gt;
- 					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
- 						&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
- 						&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
- 					&lt;/section&gt;
- 					&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
- 						&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
- 							&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
- 							&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
- 						&lt;/div&gt;
- 					&lt;/section&gt;
- 					&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
- 						&lt;h2&gt;... and GIFs!&lt;/h2&gt;
- 					&lt;/section&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
- 					&lt;h2&gt;Background Transitions&lt;/h2&gt;
- 					&lt;p&gt;
- 						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
- 					&lt;/p&gt;
- 					&lt;pre&gt;&lt;code class="hljs"&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;&lt;/pre&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
- 					&lt;h2&gt;Background Transitions&lt;/h2&gt;
- 					&lt;p&gt;
- 						You can override background transitions per-slide.
- 					&lt;/p&gt;
- 					&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Pretty Code&lt;/h2&gt;
- 					&lt;pre&gt;&lt;code class="hljs" data-trim contenteditable&gt;
- function linkify( selector ) {
-   if( supports3DTransforms ) {
- 
-     var nodes = document.querySelectorAll( selector );
- 
-     for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
-       var node = nodes[i];
- 
-       if( !node.className ) {
-         node.className += ' roll';
-       }
-     }
-   }
- }
- 					&lt;/code&gt;&lt;/pre&gt;
- 					&lt;p&gt;Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Marvelous List&lt;/h2&gt;
- 					&lt;ul&gt;
- 						&lt;li&gt;No order here&lt;/li&gt;
- 						&lt;li&gt;Or here&lt;/li&gt;
- 						&lt;li&gt;Or here&lt;/li&gt;
- 						&lt;li&gt;Or here&lt;/li&gt;
- 					&lt;/ul&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
- 					&lt;ol&gt;
- 						&lt;li&gt;One is smaller than...&lt;/li&gt;
- 						&lt;li&gt;Two is smaller than...&lt;/li&gt;
- 						&lt;li&gt;Three!&lt;/li&gt;
- 					&lt;/ol&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Tabular Tables&lt;/h2&gt;
- 					&lt;table&gt;
- 						&lt;thead&gt;
- 							&lt;tr&gt;
- 								&lt;th&gt;Item&lt;/th&gt;
- 								&lt;th&gt;Value&lt;/th&gt;
- 								&lt;th&gt;Quantity&lt;/th&gt;
- 							&lt;/tr&gt;
- 						&lt;/thead&gt;
- 						&lt;tbody&gt;
- 							&lt;tr&gt;
- 								&lt;td&gt;Apples&lt;/td&gt;
- 								&lt;td&gt;$1&lt;/td&gt;
- 								&lt;td&gt;7&lt;/td&gt;
- 							&lt;/tr&gt;
- 							&lt;tr&gt;
- 								&lt;td&gt;Lemonade&lt;/td&gt;
- 								&lt;td&gt;$2&lt;/td&gt;
- 								&lt;td&gt;18&lt;/td&gt;
- 							&lt;/tr&gt;
- 							&lt;tr&gt;
- 								&lt;td&gt;Bread&lt;/td&gt;
- 								&lt;td&gt;$3&lt;/td&gt;
- 								&lt;td&gt;2&lt;/td&gt;
- 							&lt;/tr&gt;
- 						&lt;/tbody&gt;
- 					&lt;/table&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Clever Quotes&lt;/h2&gt;
- 					&lt;p&gt;
- 						These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
- 						&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
- 					&lt;/p&gt;
- 					&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
- 						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
- 						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
- 					&lt;/blockquote&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
- 					&lt;p&gt;
- 						You can link between slides internally,
- 						&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Speaker View&lt;/h2&gt;
- 					&lt;p&gt;There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.&lt;/p&gt;
- 					&lt;p&gt;Press the &lt;em&gt;S&lt;/em&gt; key to try it out.&lt;/p&gt;
- 
- 					&lt;aside class="notes"&gt;
- 						Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
- 					&lt;/aside&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Export to PDF&lt;/h2&gt;
- 					&lt;p&gt;Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:&lt;/p&gt;
- 					&lt;iframe data-src="https://www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Global State&lt;/h2&gt;
- 					&lt;p&gt;
- 						Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and &lt;code&gt;"something"&lt;/code&gt;
- 						will be added as a class to the document element when the slide is open. This lets you
- 						apply broader style changes, like switching the page background.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section data-state="customevent"&gt;
- 					&lt;h2&gt;State Events&lt;/h2&gt;
- 					&lt;p&gt;
- 						Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
- 					&lt;/p&gt;
- 					&lt;pre&gt;&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
- Reveal.addEventListener( 'customevent', function() {
- 	console.log( '"customevent" has fired' );
- } );
- 					&lt;/code&gt;&lt;/pre&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Take a Moment&lt;/h2&gt;
- 					&lt;p&gt;
- 						Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Much more&lt;/h2&gt;
- 					&lt;ul&gt;
- 						&lt;li&gt;Right-to-left support&lt;/li&gt;
- 						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;&lt;/li&gt;
- 						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;&lt;/li&gt;
- 						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;&lt;/li&gt;
- 						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;&lt;/li&gt;
- 					&lt;/ul&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section style="text-align: left;"&gt;
- 					&lt;h1&gt;THE END&lt;/h1&gt;
- 					&lt;p&gt;
- 						- &lt;a href="http://slides.com"&gt;Try the online editor&lt;/a&gt; &lt;br&gt;
- 						- &lt;a href="https://github.com/hakimel/reveal.js"&gt;Source code &amp;amp; documentation&lt;/a&gt;
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 			&lt;/div&gt;
- 
- 		&lt;/div&gt;
- 
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
- 
- 		&lt;script&gt;
- 
- 			// More info https://github.com/hakimel/reveal.js#configuration
- 			Reveal.initialize({
- 				controls: true,
- 				progress: true,
- 				history: true,
- 				center: true,
- 
- 				transition: 'slide', // none/fade/slide/convex/concave/zoom
- 
- 				// More info https://github.com/hakimel/reveal.js#dependencies
? ^^^^
+             // More info https://github.com/hakimel/reveal.js#dependencies
? ^^^^^^^^^^^^
- 				dependencies: [
+             dependencies: [
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
? ^^^^^^^^^^^^^^^^                                                                                          +
- 				]
- 			});
- 
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
+             ]
+         });
- 		&lt;/script&gt;
? --
+ &lt;/script&gt;
- 
- 	&lt;/body&gt;
? -
+ &lt;/body&gt;
</t>
<t tx="leo.20161118210944.60">(uncached) yen.20161011121637.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.61">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.62">@others
</t>
<t tx="leo.20161118210944.63">(uncached) yen.20161011121637.2
Diff...
+ # 自學的訓練
+ 
+ ## 學員必須自己有學習動機
+ ## 能消化中英文資料
+ ## 從中體會學習的意義
+ 
+ 
</t>
<t tx="leo.20161118210944.64"># 自學的訓練

## 學員必須自己有學習動機
## 能消化中英文資料
## 從中體會學習的意義


</t>
<t tx="leo.20161118210944.65"></t>
<t tx="leo.20161118210944.66">(uncached) amd.20161004105716.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.67">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.68">@others
</t>
<t tx="leo.20161118210944.69">(uncached) amd.20161004105716.2
Diff...
+ # 高效執行力
+ 
+ ## 用對的方法
+ ## 在對的時機
+ ## 找對的人
+ ## 作對的事
+ 
+ 
</t>
<t tx="leo.20161118210944.7">&lt;body&gt;
@others
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
        // More info https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            controls: true,
            progress: true,
            history: true,
            center: true,

            transition: 'slide', // none/fade/slide/convex/concave/zoom

            // More info https://github.com/hakimel/reveal.js#dependencies
            dependencies: [
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
            ]
        });
&lt;/script&gt;
&lt;/body&gt;
</t>
<t tx="leo.20161118210944.70"># 高效執行力

## 用對的方法
## 在對的時機
## 找對的人
## 作對的事


</t>
<t tx="leo.20161118210944.71"></t>
<t tx="leo.20161118210944.72">(uncached) yen.20161016004633.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;
</t>
<t tx="leo.20161118210944.73">&lt;section&gt;
@others
&lt;/section&gt;
</t>
<t tx="leo.20161118210944.74">@others
</t>
<t tx="leo.20161118210944.75">(uncached) yen.20161016004633.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.76">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.77">@others
</t>
<t tx="leo.20161118210944.78">(uncached) yen.20161016004633.5
Diff...
+ # 計算機程式課程規劃
+ 
+ ## [課程規劃](https://github.com/mdecourse/2016fallcp/blob/master/syllabus.py)
+ ## [課程 Wiki](https://github.com/mdecourse/2016fallcp/wiki)
+ ## [課程網誌](http://chiamingyen.github.io/kmolab/blog/tag/2016fallcp.html)
+ 
</t>
<t tx="leo.20161118210944.79"># 計算機程式課程規劃

## [課程規劃](https://github.com/mdecourse/2016fallcp/blob/master/syllabus.py)
## [課程 Wiki](https://github.com/mdecourse/2016fallcp/wiki)
## [課程網誌](http://chiamingyen.github.io/kmolab/blog/tag/2016fallcp.html)

</t>
<t tx="leo.20161118210944.8">
@others
				&lt;section&gt;
					&lt;section&gt;
						&lt;h2&gt;Vertical Slides&lt;/h2&gt;
						&lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
						&lt;p&gt;Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.&lt;/p&gt;
						&lt;br&gt;
						&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 1&lt;/h2&gt;
						&lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
						&lt;br&gt;
						&lt;a href="#/2"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Slides&lt;/h2&gt;
					&lt;p&gt;
						Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Point of View&lt;/h2&gt;
					&lt;p&gt;
						Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
					&lt;/p&gt;
					&lt;p&gt;
						Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Touch Optimized&lt;/h2&gt;
					&lt;p&gt;
						Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section data-markdown&gt;
					&lt;script type="text/template"&gt;
						## Markdown support

						Write content using inline or external Markdown.
						Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).

						```
						&lt;section data-markdown&gt;
						  ## Markdown support

						  Write content using inline or external Markdown.
						  Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
						&lt;/section&gt;
						```
					&lt;/script&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section id="fragments"&gt;
						&lt;h2&gt;Fragments&lt;/h2&gt;
						&lt;p&gt;Hit the next arrow...&lt;/p&gt;
						&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
						&lt;p&gt;&lt;span class="fragment"&gt;... a&lt;/span&gt; &lt;span class="fragment"&gt;fragmented&lt;/span&gt; &lt;span class="fragment"&gt;slide.&lt;/span&gt;&lt;/p&gt;

						&lt;aside class="notes"&gt;
							This slide has fragments which are also stepped through in the notes window.
						&lt;/aside&gt;
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Fragment Styles&lt;/h2&gt;
						&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						&lt;p class="fragment fade-up"&gt;fade-up (also down, left and right!)&lt;/p&gt;
						&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						&lt;p&gt;Highlight &lt;span class="fragment highlight-red"&gt;red&lt;/span&gt; &lt;span class="fragment highlight-blue"&gt;blue&lt;/span&gt; &lt;span class="fragment highlight-green"&gt;green&lt;/span&gt;&lt;/p&gt;
					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section id="transitions"&gt;
					&lt;h2&gt;Transition Styles&lt;/h2&gt;
					&lt;p&gt;
						You can select from different transitions, like: &lt;br&gt;
						&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
						&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section id="themes"&gt;
					&lt;h2&gt;Themes&lt;/h2&gt;
					&lt;p&gt;
						reveal.js comes with a few themes built in: &lt;br&gt;
						&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; &lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						&lt;p&gt;
							Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
						&lt;/p&gt;
						&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						&lt;pre&gt;&lt;code class="hljs"&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
						&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
					&lt;/section&gt;
					&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
							&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
							&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
						&lt;/div&gt;
					&lt;/section&gt;
					&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
						&lt;h2&gt;... and GIFs!&lt;/h2&gt;
					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
					&lt;h2&gt;Background Transitions&lt;/h2&gt;
					&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					&lt;pre&gt;&lt;code class="hljs"&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					&lt;h2&gt;Background Transitions&lt;/h2&gt;
					&lt;p&gt;
						You can override background transitions per-slide.
					&lt;/p&gt;
					&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Pretty Code&lt;/h2&gt;
					&lt;pre&gt;&lt;code class="hljs" data-trim contenteditable&gt;
function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
					&lt;/code&gt;&lt;/pre&gt;
					&lt;p&gt;Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Marvelous List&lt;/h2&gt;
					&lt;ul&gt;
						&lt;li&gt;No order here&lt;/li&gt;
						&lt;li&gt;Or here&lt;/li&gt;
						&lt;li&gt;Or here&lt;/li&gt;
						&lt;li&gt;Or here&lt;/li&gt;
					&lt;/ul&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					&lt;ol&gt;
						&lt;li&gt;One is smaller than...&lt;/li&gt;
						&lt;li&gt;Two is smaller than...&lt;/li&gt;
						&lt;li&gt;Three!&lt;/li&gt;
					&lt;/ol&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					&lt;table&gt;
						&lt;thead&gt;
							&lt;tr&gt;
								&lt;th&gt;Item&lt;/th&gt;
								&lt;th&gt;Value&lt;/th&gt;
								&lt;th&gt;Quantity&lt;/th&gt;
							&lt;/tr&gt;
						&lt;/thead&gt;
						&lt;tbody&gt;
							&lt;tr&gt;
								&lt;td&gt;Apples&lt;/td&gt;
								&lt;td&gt;$1&lt;/td&gt;
								&lt;td&gt;7&lt;/td&gt;
							&lt;/tr&gt;
							&lt;tr&gt;
								&lt;td&gt;Lemonade&lt;/td&gt;
								&lt;td&gt;$2&lt;/td&gt;
								&lt;td&gt;18&lt;/td&gt;
							&lt;/tr&gt;
							&lt;tr&gt;
								&lt;td&gt;Bread&lt;/td&gt;
								&lt;td&gt;$3&lt;/td&gt;
								&lt;td&gt;2&lt;/td&gt;
							&lt;/tr&gt;
						&lt;/tbody&gt;
					&lt;/table&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					&lt;p&gt;
						These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
					&lt;/p&gt;
					&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
					&lt;/blockquote&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					&lt;p&gt;
						You can link between slides internally,
						&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Speaker View&lt;/h2&gt;
					&lt;p&gt;There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.&lt;/p&gt;
					&lt;p&gt;Press the &lt;em&gt;S&lt;/em&gt; key to try it out.&lt;/p&gt;

					&lt;aside class="notes"&gt;
						Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
					&lt;/aside&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Export to PDF&lt;/h2&gt;
					&lt;p&gt;Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:&lt;/p&gt;
					&lt;iframe data-src="https://www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Global State&lt;/h2&gt;
					&lt;p&gt;
						Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and &lt;code&gt;"something"&lt;/code&gt;
						will be added as a class to the document element when the slide is open. This lets you
						apply broader style changes, like switching the page background.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section data-state="customevent"&gt;
					&lt;h2&gt;State Events&lt;/h2&gt;
					&lt;p&gt;
						Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
					&lt;/p&gt;
					&lt;pre&gt;&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Take a Moment&lt;/h2&gt;
					&lt;p&gt;
						Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Much more&lt;/h2&gt;
					&lt;ul&gt;
						&lt;li&gt;Right-to-left support&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;&lt;/li&gt;
					&lt;/ul&gt;
				&lt;/section&gt;

				&lt;section style="text-align: left;"&gt;
					&lt;h1&gt;THE END&lt;/h1&gt;
					&lt;p&gt;
						- &lt;a href="http://slides.com"&gt;Try the online editor&lt;/a&gt; &lt;br&gt;
						- &lt;a href="https://github.com/hakimel/reveal.js"&gt;Source code &amp;amp; documentation&lt;/a&gt;
					&lt;/p&gt;
				&lt;/section&gt;

			&lt;/div&gt;

		&lt;/div&gt;

		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;

		&lt;script&gt;

			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	&lt;/body&gt;
</t>
<t tx="leo.20161118210944.80"></t>
<t tx="leo.20161118210944.81">(uncached) yen.20161016010643.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.82">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.83">@others
</t>
<t tx="leo.20161118210944.84">(uncached) yen.20161016010643.2
Diff...
+ ## 下載 miniconda 可攜環境
+ 
+   * 在電腦教室下載 [mini2016fall.7z](http://140.130.17.17/public/2016fall/mini2016fall_with_leo.7z)
+   * 從外部下載 [mini2016fall.7z](https://140.130.17.101/download/?filepath=/home/yen/cmsimply/wsgi/local_data/downloads/mini2016fall_with_leo.7z)
+   * start.bat 啟動, stop.bat 關閉
+   * 建議存在隨身硬碟中使用
+ 
+ 
</t>
<t tx="leo.20161118210944.85">## 下載 miniconda 可攜環境

  * 在電腦教室下載 [mini2016fall.7z](http://140.130.17.17/public/2016fall/mini2016fall_with_leo.7z)
  * 從外部下載 [mini2016fall.7z](https://140.130.17.101/download/?filepath=/home/yen/cmsimply/wsgi/local_data/downloads/mini2016fall_with_leo.7z)
  * start.bat 啟動, stop.bat 關閉
  * 建議存在隨身硬碟中使用


</t>
<t tx="leo.20161118210944.86"></t>
<t tx="leo.20161118210944.87">(uncached) yen.20161016010719.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.88">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.89">@others
</t>
<t tx="leo.20161118210944.9">(uncached) amd.20161004083800.6
Diff...
- 	&lt;body&gt;
+ &lt;div class="reveal"&gt;
  @others
-                               
- 				&lt;!-- Example of nested vertical slides --&gt;
+ &lt;/div&gt;
+ 
</t>
<t tx="leo.20161118210944.90">(uncached) yen.20161016012922.1
Diff...
+ ## 學員自評項目
+ 
+ * 上課筆記與心得寫在個人的 2016fallcp_hw 倉儲 Wiki 中
+ * 利用 [ShareX](https://getsharex.com/) 錄製上課操作練習影片
+ * 將影片加上說明字幕後, 上傳至個人 [Vimeo](https://vimeo.com/) 與 [Youtube](https://www.youtube.com)
+ * 每週更新個人與分組的 Github Pages 投影片與網誌</t>
<t tx="leo.20161118210944.91">## 學員自評項目

* 上課筆記與心得寫在個人的 2016fallcp_hw 倉儲 Wiki 中
* 利用 [ShareX](https://getsharex.com/) 錄製上課操作練習影片
* 將影片加上說明字幕後, 上傳至個人 [Vimeo](https://vimeo.com/) 與 [Youtube](https://www.youtube.com)
* 每週更新個人與分組的 Github Pages 投影片與網誌</t>
<t tx="leo.20161118210944.92"></t>
<t tx="leo.20161118210944.93">(uncached) yen.20161011122932.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161118210944.94">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161118210944.95">@others
</t>
<t tx="leo.20161118210944.96">(uncached) yen.20161011122601.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161118210944.97">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161118210944.98">@others
</t>
<t tx="leo.20161118210944.99">(uncached) yen.20161011122601.2
Diff...
+ # 自學 Python3
+ 
+ [Python3 程式範例](https://github.com/mdecourse/2016fallcp/blob/master/python3program.py)
+ ### 在哪裡執行?
+ ### 如何執行?
+ ### 如何寫心得?
+ ### 如何錄製操作過程?
</t>
<t tx="leo.20161209142134.1">@language python
import os
import subprocess
import threading
import socket
import http.server, ssl

class HTTPServerV6(http.server.HTTPServer):
    address_family = socket.AF_INET6
  
def domake():
    # build directory
    os.chdir("./../")
    ipv6_address = '2001:0:9d38:6ab8:1cb0:c047:c222:a9e9'
    server_address = (ipv6_address, 6443)
    #httpd = http.server.HTTPServer(server_address, http.server.SimpleHTTPRequestHandler)
    httpd = HTTPServerV6(server_address, http.server.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket(httpd.socket,
                                   server_side=True,
                                   certfile='localhost.crt',
                                   keyfile='localhost.key',
                                   ssl_version=ssl.PROTOCOL_TLSv1)
    print("6443 https server started")
    httpd.serve_forever()

# 利用執行緒執行 https 伺服器
make = threading.Thread(target=domake)
make.start()</t>
<t tx="leo.20161209142152.1">@language python
import os
import subprocess
import threading
import http.server, ssl

def domake():
    # build directory
    os.chdir("./../")
    server_address = ('localhost', 6443)
    httpd = http.server.HTTPServer(server_address, http.server.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket(httpd.socket,
                                   server_side=True,
                                   certfile='localhost.crt',
                                   keyfile='localhost.key',
                                   ssl_version=ssl.PROTOCOL_TLSv1)
    print("5443 https server started")
    httpd.serve_forever()

# 利用執行緒執行 https 伺服器
make = threading.Thread(target=domake)
make.start()</t>
<t tx="leo.20161223145325.2"></t>
<t tx="leo.20161223145325.3">(uncached) amd.20161004083800.2
Diff...
  
  	&lt;head&gt;
  		&lt;meta charset="utf-8"&gt;
  
- 		&lt;title&gt;40523123郝冠儒的計算機課程&lt;/title&gt;
+ 		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;
  
  		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
  		&lt;meta name="author" content="Hakim El Hattab"&gt;
  
  		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
  		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
  
  		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
  
  		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
  		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
  
  		&lt;!-- Theme used for syntax highlighting of code --&gt;
  		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
  
  		&lt;!-- Printing and PDF exports --&gt;
  		&lt;script&gt;
  			var link = document.createElement( 'link' );
  			link.rel = 'stylesheet';
  			link.type = 'text/css';
  			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
  			document.getElementsByTagName( 'head' )[0].appendChild( link );
  		&lt;/script&gt;
  
  		&lt;!--[if lt IE 9]&gt;
  		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
  		&lt;![endif]--&gt;
  	&lt;/head&gt;
</t>
<t tx="leo.20161223145325.4">
	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;

		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
		&lt;meta name="author" content="Hakim El Hattab"&gt;

		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;
</t>
<t tx="leo.20161223145325.5">
	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;40523123郝冠儒的計算機課程&lt;/title&gt;

		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
		&lt;meta name="author" content="Hakim El Hattab"&gt;

		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;
</t>
<t tx="leo.20161223145325.6">(uncached) amd.20161004095719.2
Diff...
  			&lt;div class="slides"&gt;
  				&lt;section&gt;
- 					&lt;h1&gt;40523123學員的計算機課程&lt;/h1&gt;
- 					&lt;h3&gt;課程內容k&lt;/h3&gt;
+ 					&lt;h1&gt;2016Fall CPA 計算機程式課程&lt;/h1&gt;
+ 					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
  					&lt;p&gt;
  						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
  					&lt;/p&gt;
                      &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
  				&lt;/section&gt;
  
</t>
<t tx="leo.20161223145325.7">			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;2016Fall CPA 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20161223145325.8">			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;40523123學員的計算機課程&lt;/h1&gt;
					&lt;h3&gt;課程內容k&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170623004106.1">&lt;h1&gt;自製網路線&lt;/h1&gt;
網路線分為8P(電腦用)及6P(電話用)。

自製網路線須備器材：

1.8P/6P網路線壓線鉗

2.8P8C網路線接頭

3.適當長度網路線</t>
<t tx="leo.20170623005150.1">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;

</t>
<t tx="leo.20170623005154.1">&lt;h1&gt;568B標準線接法&lt;/h1&gt;
此接線方式為最標準接法，任何電腦連接任何IP分享器、HUB都是用這種壓線方式。

其中線依顏色排列左至右為：

白橘、橘、白綠、藍、白藍、綠、白棕、棕。

且兩頭接法皆相同。</t>
<t tx="leo.20170623011730.1">&lt;h1&gt;568A電腦對接法&lt;/h1&gt;
此接法稱為「跳線」，是兩台電腦要互接的壓線方式。

其中線依顏色排列左至右為(兩端接頭不同)：

白橘、橘、白綠、藍、白藍、綠、白棕、棕。

白綠、綠、白橘、藍、白藍、橘、白棕、棕。

(兩端差別為綠與橘對調。)</t>
<t tx="leo.20170623011730.2">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;

</t>
<t tx="leo.20170623110900.1">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;

</t>
<t tx="leo.20170623110907.1">&lt;h1&gt;Fossil&lt;/h1&gt;

Fossil is a simple, high-reliability, distributed software configuration management system.

Integrated Bug Tracking, Wiki, and Technotes.

課程中將要在區域網路與系上主幹中配置兩台Fossil SCM主機。</t>
<t tx="leo.20170623110936.1">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;

</t>
<t tx="leo.20170623110941.1">&lt;h1&gt;CMSIMPLY&lt;/h1&gt;

CMSimply is a simple cloud based content mangement system (雲端內容管理系統) written in Python and CherryPy.

all content are saved in a file called content.htm, no database needed (不需要資料庫), uploaded files are stored into images and downloads directories, therefore it is very easy to backup your site.

CMSimply content.htm is compatible with CMSimple.</t>
<t tx="leo.20170623111355.1">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;

</t>
<t tx="leo.20170623111400.1">&lt;h1&gt;在VirtualBox中安裝Ubuntu16.04&lt;/h1&gt;

&lt;iframe src="https://player.vimeo.com/video/214364942" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;p&gt;&lt;a href="https://vimeo.com/214364942"&gt;練習在virtualBox中啟動Ubuntu&lt;/a&gt; from &lt;a href="https://vimeo.com/user58916608"&gt;KuanRu&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;</t>
<t tx="leo.20170623111404.1">&lt;h1&gt;在Ubuntu16.04中安裝nginx及設定網路&lt;/h1&gt;

&lt;iframe src="https://player.vimeo.com/video/214365006" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;p&gt;&lt;a href="https://vimeo.com/214365006"&gt;練習在Ubuntu環境下安裝nignx&lt;/a&gt; from &lt;a href="https://vimeo.com/user58916608"&gt;KuanRu&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;</t>
<t tx="leo.20170623111404.2">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;

</t>
<t tx="leo.20170623111804.1">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;

</t>
<t tx="leo.20170623111810.1">&lt;h2&gt;在Ubuntu16.04啟動Stunnel與 Fossil SCM&lt;/h2&gt;

&lt;iframe src="https://player.vimeo.com/video/214968806" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;p&gt;&lt;a href="https://vimeo.com/214968806"&gt;在Ubuntu 16.04 環境下啟動 Stunnel 與 Fossil SCM&lt;/a&gt; from &lt;a href="https://vimeo.com/user58916608"&gt;KuanRu&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;</t>
<t tx="leo.20170623112218.1">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;

</t>
<t tx="leo.20170623112223.1">&lt;h1&gt;END&lt;/h1&gt;</t>
<t tx="yen.20161022111056.1">@language python
import os
import subprocess
import threading
import http.server, ssl

def domake():
    # build directory
    os.chdir("./../")
    server_address = ('localhost', 5443)
    httpd = http.server.HTTPServer(server_address, http.server.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket(httpd.socket,
                                   server_side=True,
                                   certfile='localhost.crt',
                                   keyfile='localhost.key',
                                   ssl_version=ssl.PROTOCOL_TLSv1)
    print("5443 https server started")
    httpd.serve_forever()

# 利用執行緒執行 https 伺服器
make = threading.Thread(target=domake)
make.start()</t>
<t tx="yen.20161022151749.1">sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout localhost.key -out localhost.crt

</t>
<t tx="yen.20161105200127.1"></t>
<t tx="yen.20161105200145.1"></t>
</tnodes>
</leo_file>
